sudo: required
dist: trusty
language: python
node_js:
    - "5.5"
python:
    - "3.4"
before_install:
    - sudo apt-get -y install python3-pip python-dev
    - sudo pip3 install -U setuptools
    - sudo pip3 install -U virtualenvwrapper
    - python3 -V
    - pip3 -V
install: 
    - npm install -g gulp
    - npm install
    - sudo pip install -r requirements.txt
env:
    - CONFIG_PATH=py_ferry.config.TravisConfig
before_script:
    - psql -c 'create database "py-ferry-test";' -U postgres
    - gulp build
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
    - python3 tests/test_models_unit.py
    - python3 tests/api_integration.py
    - python3 tests/test_acceptance.py